# Site settings
title: Ladies Learning Code
subtitle: Digital Skills Program
email: info@ladieslearningcode.com
description: > # this means to ignore newlines until "baseurl:"
  Enhance your digital and technology skills. Unleash your creative potential with our 7-week part-time program!
baseurl: "/llc-digital-skills" # the subpath of your site, e.g. /blog/
url: " " # the base hostname & protocol for your site
twitter: learningcode
slack: digitalskills
facebook: ladieslearningcode

# Build settings
markdown: kramdown
style: debug
collections:
  lessons:
    output: true
    permalink: lessons/:path/
