# Site settings
title: Ladies Learning Code
subtitle: Digital Skills Program
email: info@ladieslearningcode.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. 
baseurl: "/llc-digital-skills" # the subpath of your site, e.g. /blog/
url: " " # the base hostname & protocol for your site
twitter: learningcode
slack: digitalskills.slack.com
facebook: fb.com/ladieslearningcode

# Build settings
markdown: kramdown
style: debug
collections:
  lessons:
    output: true
    permalink: lessons/:path/
