# Site settings
title: Ladies Learning Code
subtitle: Digital Skills Program
email: info@ladieslearningcode.com
description: > # this means to ignore newlines until "baseurl:"
  Enhance your digital and technology skills. Unleash your creative potential with our 7-week part-time program!
baseurl: "/llc-digital-skills" # the subpath of your site, e.g. /blog/
url: " " # the base hostname & protocol for your site
twitter: learningcode
slack: digitalskills
facebook: canadalearningcode


# Build settings
markdown: kramdown
style: debug
collections:
  lessons:
    output: true
    permalink: lessons/:path/

kramdown:
  # instruct kramdown to parse inside html block elements
  # like p, header, lists, ...
  parse_block_html: true


#File paths
css-global: assets/css/styles.css # global CSS file
css-syntax: assets/css/highlightjs/github.css # syntax highlighter CSS
jquery: assets/js/jquery-1.11.3.min.js # jQuery
js-global: assets/js/global.js # global JS file
js-syntax: assets/js/highlight.pack.js # syntax highlighter JS
js-waypoints: assets/js/jquery.waypoints.min.js # Waypoints library
img: assets/img # path to image folder
